<?xml version="1.0" encoding="utf-8"?><Database Name="labo" Class="ArticlesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=127.0.0.1\SQLEXPRESS;Initial Catalog=labo;Persist Security Info=True;User ID=labo" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="laboConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetAllArticles" Method="GetAllArticles">
    <ElementType Name="GetAllArticlesResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descriptif" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="promo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="idImg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="img" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetArticle" Method="GetArticle">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetArticleResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descriptif" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="promo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="idImg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="img" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>