<?xml version="1.0" encoding="utf-8"?><Database Name="labo" Class="TransactUserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=127.0.0.1\SQLEXPRESS;Initial Catalog=labo;Persist Security Info=True;User ID=labo" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="laboConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TransactSqlUser" Member="TransactSqlUser">
    <Type Name="TransactSqlUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.AddUserTransact" Method="AddUserTransact">
    <Parameter Name="Nom" Parameter="nom" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>