#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_ex_janvier_2018.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="examenJanvier2018")]
	public partial class LinkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    #endregion
		
		public LinkDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["examenJanvier2018ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAll")]
		public ISingleResult<GetAllResult> GetAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AjaxGetImage")]
		public ISingleResult<AjaxGetImageResult> AjaxGetImage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<AjaxGetImageResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllGenre")]
		public ISingleResult<GetAllGenreResult> GetAllGenre()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllGenreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCollection")]
		public ISingleResult<GetCollectionResult> GetCollection()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetCollectionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateArticle")]
		public int UpdateArticle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> articleid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> genreid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> collectionId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string desc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), articleid, genreid, collectionId, nom, desc);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class GetAllResult
	{
		
		private System.Guid _ArticleId;
		
		private System.Guid _GenreId;
		
		private System.Data.Linq.Binary _Photo;
		
		private string _Nom;
		
		private string _Descriptif;
		
		private double _Prix;
		
		private int _Stock;
		
		private System.Guid _CollId;
		
		private bool _Solde;
		
		private string _ColNom;
		
		private string _Gnom;
		
		public GetAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArticleId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ArticleId
		{
			get
			{
				return this._ArticleId;
			}
			set
			{
				if ((this._ArticleId != value))
				{
					this._ArticleId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenreId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GenreId
		{
			get
			{
				return this._GenreId;
			}
			set
			{
				if ((this._GenreId != value))
				{
					this._GenreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="Image")]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this._Photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descriptif", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descriptif
		{
			get
			{
				return this._Descriptif;
			}
			set
			{
				if ((this._Descriptif != value))
				{
					this._Descriptif = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prix", DbType="Float NOT NULL")]
		public double Prix
		{
			get
			{
				return this._Prix;
			}
			set
			{
				if ((this._Prix != value))
				{
					this._Prix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int NOT NULL")]
		public int Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this._Stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CollId
		{
			get
			{
				return this._CollId;
			}
			set
			{
				if ((this._CollId != value))
				{
					this._CollId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solde", DbType="Bit NOT NULL")]
		public bool Solde
		{
			get
			{
				return this._Solde;
			}
			set
			{
				if ((this._Solde != value))
				{
					this._Solde = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColNom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ColNom
		{
			get
			{
				return this._ColNom;
			}
			set
			{
				if ((this._ColNom != value))
				{
					this._ColNom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gnom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gnom
		{
			get
			{
				return this._Gnom;
			}
			set
			{
				if ((this._Gnom != value))
				{
					this._Gnom = value;
				}
			}
		}
	}
	
	public partial class AjaxGetImageResult
	{
		
		private System.Data.Linq.Binary _Photo;
		
		public AjaxGetImageResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="Image")]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this._Photo = value;
				}
			}
		}
	}
	
	public partial class GetAllGenreResult
	{
		
		private System.Guid _GenreId;
		
		private string _Gnom;
		
		public GetAllGenreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenreId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GenreId
		{
			get
			{
				return this._GenreId;
			}
			set
			{
				if ((this._GenreId != value))
				{
					this._GenreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gnom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gnom
		{
			get
			{
				return this._Gnom;
			}
			set
			{
				if ((this._Gnom != value))
				{
					this._Gnom = value;
				}
			}
		}
	}
	
	public partial class GetCollectionResult
	{
		
		private string _ColNom;
		
		private System.Guid _CollectionId;
		
		public GetCollectionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColNom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ColNom
		{
			get
			{
				return this._ColNom;
			}
			set
			{
				if ((this._ColNom != value))
				{
					this._ColNom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectionId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CollectionId
		{
			get
			{
				return this._CollectionId;
			}
			set
			{
				if ((this._CollectionId != value))
				{
					this._CollectionId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
