<?xml version="1.0" encoding="utf-8"?><Database Name="labo" Class="User2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=127.0.0.1\SQLEXPRESS;Initial Catalog=labo;Persist Security Info=True;User ID=labo" SettingsObjectName="Trombinoscope.Properties.Settings" SettingsPropertyName="laboConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users" Id="ID1">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prenom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Adresse" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CodePostal" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ville" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdImg" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetAllFromUserId" Method="GetAllFromUserId">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.GetListOfUsers" Method="GetListOfUsers">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.UpdateUser" Method="UpdateUser">
    <Parameter Name="IdUser" Parameter="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nom" Parameter="nom" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="Prenom" Parameter="prenom" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="Tel" Parameter="tel" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="Adresse" Parameter="adresse" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="CodePostal" Parameter="codePostal" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="Ville" Parameter="ville" Type="System.String" DbType="NVarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddUser" Method="AddUser">
    <Parameter Name="Nom" Parameter="nom" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Prenom" Parameter="prenom" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Tel" Parameter="tel" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Adresse" Parameter="adresse" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CodePostal" Parameter="codePostal" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ville" Parameter="ville" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteUser" Method="DeleteUser">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>